"""empty message

Revision ID: cf7601b5d3f5
Revises: 
Create Date: 2020-11-20 07:08:29.786616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7601b5d3f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    actor_table = op.create_table('Actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    movie_table = op.create_table('Movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    actor_data=[{
        "id": 1,
        "name":"Lee Byung-hun",
        "age":50,
        "gender":"male",
    },{
        "id": 2,
        "name":"Won Bin",
        "age":43,
        "gender":"male",
    },{
        "id": 3,
        "name":"Song Hye-kyo",
        "age":39,
        "gender":"female",         
    }]

    movie_data=[{
        "id": 1,
        "title":"Hwang Jin Yin",
        "release_date":"2007-07-06T00:00:00.000Z",
    },{
        "id": 2,
        "title":"The Age of Shadows",
        "release_date":"2016-09-07T00:00:00.000Z",
    }]
    op.bulk_insert(actor_table, actor_data)
    op.bulk_insert(movie_table, movie_data)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Movie')
    op.drop_table('Actor')
    # ### end Alembic commands ###
